; Generated by AutoGUI 2.5.3
#SingleInstance Force
#NoEnv
#InstallKeybdHook
#InstallMouseHook
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui -MaximizeBox
Gui Add, Text, x16 y8 w120 h21, A_TimeIdle
Gui Add, Text, x16 y40 w120 h21, A_TimeIdlePhysical
Gui Add, Text, x16 y72 w120 h21, A_TimeIdleMouse
Gui Add, Text, x16 y104 w120 h21, A_TimeIdleKeyboard
Gui Add, Edit, x144 y8 w120 h21 +ReadOnly, 0
Gui Add, Edit, x144 y40 w120 h21 +ReadOnly, 0
Gui Add, Edit, x144 y72 w120 h21 +ReadOnly, 0
Gui Add, Edit, x144 y104 w120 h21 +ReadOnly, 0

Gui Show, w276 h133, AHK IdleTimes
SetTimer, Loop, 1
Return
Loop:
    Gui,+LastFound
    ControlSetText,Edit1, %A_TimeIdle%
    ControlSetText,Edit2, %A_TimeIdlePhysical%
    ControlSetText,Edit3, %A_TimeIdleMouse%
    ControlSetText,Edit4, %A_TimeIdleKeyboard%
    Return
GuiEscape:
GuiClose:
    ExitApp
