; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

#Include %A_ScriptDir%\AutoXYWH.ahk

Gui Main: New, +LabelMain +hWndhMainWnd -Resize
Gui Font, s20
Gui Add, Button, hWndhBtnNum vBtnNum gnum x32 y24 w200 h180, &NUM
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnAnd vBtnAnd gand x256 y24 w200 h180, &/
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnstar vBtnstar gstar x480 y24 w200 h180, &*
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnminus vBtnminus gminus x704 y24 w200 h180, &-
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnpos1 vBtnpos1 gpos1 x32 y224 w200 h180, &7`nPOS1
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn8 vBtn8 g8 x256 y224 w200 h180, &8`n↑
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn9 vBtn9 g9 x480 y224 w200 h180, 9`nPGUP
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn4 vBtn4 g4 x32 y424 w200 h180, &4`n←
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn5 vBtn5 g5 x256 y424 w200 h180, &5
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn6 vBtn6 g6 x480 y424 w200 h180, &6`n→
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnplus vBtnplus gplus x704 y224 w200 h373, &+
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnend vBtnend gend x32 y624 w200 h180, &1`nEND
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn2 vBtn2 g2 x256 y624 w200 h180, &2`n↓
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn3 vBtn3 g3 x480 y624 w200 h180, &3`nPGDN
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnEnter vBtnEnter gEnter x704 y624 w200 h371, &ENTER
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtn0 vBtn0 g0 x32 y824 w424 h180, &0
Gui Font
Gui Font, s20
Gui Add, Button, hWndhBtnNdel vBtnNdel gdel x480 y824 w200 h180, &,`nDEL
Gui Font

Gui Show, w936 h1025, Virtual Numpad
Return

num(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

and(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

star(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

minus(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

pos1(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

8(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

9(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

4(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

5(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

6(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

plus(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

end(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

2(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

3(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

Enter(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

0(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

del(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

MainSize(GuiHwnd, EventInfo, Width, Height) {
    If (A_EventInfo == 1) {
        Return
    }

    AutoXYWH("xywh", hBtnNum)
    AutoXYWH("xywh", hBtnAnd)
    AutoXYWH("xywh", hBtnstar)
    AutoXYWH("xywh", hBtnminus)
    AutoXYWH("xywh", hBtnpos1)
    AutoXYWH("xywh", hBtn8)
    AutoXYWH("xywh", hBtn9)
    AutoXYWH("xywh", hBtn4)
    AutoXYWH("xywh", hBtn5)
    AutoXYWH("xywh", hBtn6)
    AutoXYWH("xywh", hBtnplus)
    AutoXYWH("xywh", hBtnend)
    AutoXYWH("xywh", hBtn2)
    AutoXYWH("xywh", hBtn3)
    AutoXYWH("xywh", hBtnEnter)
    AutoXYWH("xywh", hBtn0)
    AutoXYWH("xywh", hBtnNdel)
}

MainEscape(GuiHwnd) {
    ExitApp
}

MainClose(GuiHwnd) {
    ExitApp
}
