; Generated by AutoGUI 2.5.3
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +Resize
Gui Add, Text, x8 y24 w21 h23 +0x200, X:
Gui Add, Edit, x32 y24 w55 h21 +ReadOnly
Gui Add, Text, x96 y24 w20 h23 +0x200, Y:
Gui Add, Edit, x120 y24 w57 h21 +ReadOnly
Gui Add, Text, x8 y64 w31 h23 +0x200, Color:
Gui Add, Edit, x48 y64 w129 h21 +ReadOnly
Gui Add, Text, x8 y104 w14 h23 +0x200, R:
Gui Add, Edit, x32 y104 w37 h21 +ReadOnly
Gui Add, Text, x8 y136 w14 h23 +0x200, G:
Gui Add, Edit, x32 y136 w38 h21 +ReadOnly
Gui Add, Text, x8 y168 w16 h23 +0x200, B:
Gui Add, Edit, x32 y168 w37 h21 +ReadOnly
Gui Add, Text, x8 y208 w44 h23 +0x200, Window:
Gui Add, Edit, x56 y208 w697 h21 +ReadOnly

Gui Show, w201 h245, Pixel Color
SetTimer, Loop, 1000
Return
Loop:
    Gui,+LastFound
    MouseGetPos, MouseX, MouseY, MouseWin, MouseCntrl
    PixelGetColor, color, %MouseX%, %MouseY%
    ControlSetText,Edit1, %MouseX%
    ControlSetText,Edit2, %MouseY%
    ControlSetText,Edit3, %color%
    Red:="0x" SubStr(color,7,2)
    Red:=Red+0
    ControlSetText,Edit4, %Red%
    Green:="0x" SubStr(color,5,2)
    Green:=Green+0
    ControlSetText,Edit5, %Green%
    Blue:="0x" SubStr(color,3,2)
    Blue:=Blue+0
    ControlSetText,Edit6, %Blue%
    WinGetTitle, title, ahk_id %MouseWin%
    WinGetClass, class, ahk_id %MouseWin%
    WinGet, exe, ProcessName, MouseWin
    ControlSetText,Edit7, %title% ahk_class %class% ahk_exe %exe%
    ; ControlSetText,Edit8, %MouseCntrl%
    Return

GuiEscape:
GuiClose:
    ExitApp
