name: AutoHotKey CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  prepare_ahk:
    runs-on: windows-latest
    steps:
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "ahk2exe.exe"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/Ahk2Exe.exe"
    - uses: engineerd/configurator@v0.0.8
      with:
      
        name: "unicode_x64.bin"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/Unicode 64-bit.bin"
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "unicode_x86.bin"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/Unicode 32-bit.bin"
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "ansi_x86.bin"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/ANSI 32-bit.bin"

    - uses: engineerd/configurator@v0.0.8
      with:
        name: "upx.exe"
        fromGitHubReleases: "true"
        includePrereleases: "true"
        version: "latest"
        repo: "upx/upx"
        urlTemplate: "https://github.com/upx/upx/releases/download/{{version}}/upx-{{version}}-win64.zip"

  build:
    needs: prepare_ahk
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile script
      run: |
        New-Item -ItemType Directory -Path "./bin"
        Get-ChildItem -Path . -Recurse -Filter *.ahk |ForEach-Object {
          Write-Host "Compiling '$($_.FullName)'..."
          # $_.Directory.CreateSubdirectory("bin")
          ahk2exe /in "$_.FullName" /out "./bin/$_.Name /base unicode_x64.bin /compress 2 /cp 65001"
        }
