name: AutoHotKey CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "ahk2exe.exe"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/Ahk2Exe.exe"

    - uses: engineerd/configurator@v0.0.8
      with:
        name: "unicode_x64.bin"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/Unicode 64-bit.bin"
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "unicode_x86.bin"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/Unicode 32-bit.bin"
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "ansi_x86.bin"
        url: "https://www.autohotkey.com/download/ahk.zip"
        pathInArchive: "Compiler/ANSI 32-bit.bin"

    - uses: engineerd/configurator@v0.0.8
      with:
        name: "upx.exe"
        url: "https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip"
        pathInArchive: "upx-3.96-win64/upx.exe"
    - uses: actions/checkout@v2
    - name: Compile script
      run: |
        New-Item -ItemType Directory -Path "bin"
        Get-ChildItem -Path "scripts/" -Recurse -Filter *.ahk |ForEach-Object {
          Write-Host "Compiling \"$($_.FullName)\" into \"bin/$($_.Name).exe\""
          # $_.Directory.CreateSubdirectory("bin")
          & ahk2exe.exe /in $_.FullName /out bin/$_.Name.exe /base unicode_x64.bin
        }
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bin
        path: "bin"
        retention-days: 365
